### ISSUE TITLE
Incorrect sample

### ISSUE THREAD

**Issue by Arual90** [PolymerElements/app-localize-behavior#14]
Hi, hope this is useful.

The sample code copied as it is throws the error:
_Uncaught (in promise) Error: A value must be provided for: name(…)_

After i while i found out i needed to add a parameter to localize()
`localize('hello', 'name', 'Batman')`
This way the behavior works

**Comment by notwaldorf** [comment]
Oh, thanks! Would you like to send a small PR to fix this?
