### ISSUE TITLE
No clear documentation regarding polymer vs format.js syntax

### ISSUE THREAD

**Issue by Mindcraft1** [PolymerElements/app-localize-behavior#24]
### Description

I'm doing some trials with Polymers app-localize-behavior, and I'm having a hard time to find some clear documentation regarding how to use format.js's {select} Format  found [here][1].

The app-localization-behavior documentation says : 
<br>
**"Polymer.AppLocalizeBehavior supports the same message-syntax of format.js, in its entirety;"**
<br>
But for example in the polymer docs they pass the arguments as strings: 

    {{localize('hello', 'Batman')}}

and in format.js docs not:

    I have {numCats, number} cats.

Now the issue I'm facing is how to use the {select} Format.

The format.js [docs][1] says to use it like this:

    {gender, select,
    male {He}
    female {She}
    other {They}
    } will respond shortly.

so I did this in my template: 

    {{localize(wir, select,
                wir {we}
                ich {i}
               )
    }}

locales.json : 

    {
	"en" : {
             "i" : "I",
             "we" : "we"		
	       },
	"fr" : { 

		     "i" : "je",
		     "we" : "nous"
		   },
	"de" : {
             "i" : "ich",
             "we" : "wir"
		   }
    }

### Expected outcome

The language is set by default to french `"fr"`, so I expect to get "nous" as output.

The last I did, was trying to pass everything as string or just some of the arguments (all combinations) but this all doesn't helps.

For example : 

`{{localize('wir', select,
                'wir' {we}
                'ich' {i}
               )
    }}`

  [1]: http://formatjs.io/guides/message-syntax/

### Actual outcome

Instead of "nous" the full `{{localize(etc..)}}` is displayed on screen.

### Improvements

I think the documentation should be much clearer about this.

Could you please ewxplain to me, what I'm doing wrong here?

**Comment by Mindcraft1** [comment]
Well I completely misunderstood, how format.js works and got an answer [here].(http://stackoverflow.com/questions/37918558/use-select-format-format-js-with-polymers-app-localize-behavior/37921672#37921672)

**Comment by notwaldorf** [comment]
@Mindcraft1 Glad you sorted it out! 🎉

**Comment by LRagji** [comment]
I know this is closed issue but can you guys help i am still trying to find out how formatting number works.. if someone can help me with a code pen or snippet
