### ISSUE TITLE
IE10 JavaScript errors: Unable to set property 'messages' of undefined or null reference

### ISSUE THREAD

**Issue by dlockhart** [PolymerElements/app-localize-behavior#29]
### Description

In IE10 (yeah, sorry), using `app-localize-behavior` causes a JavaScript error:

> Unable to set property 'messages' of undefined or null reference

This occurs when it tries to manipulate the prototype's `__localizationCache` object on [lines 204, 214 and 218](https://github.com/PolymerElements/app-localize-behavior/blob/master/app-localize-behavior.html#L204). For whatever reason in IE10, `this.constructor.prototype.__localizationCache` is undefined.

**Note**: this is not a result of a missing Intl polyfill, as I've tested with the polyfill (still fails) and by wrapping these checks in `if-`statements (it works).
### Expected outcome

Localization works in IE10 as it does in other browsers.
### Actual outcome

JavaScript error:

![ie10 error](https://cloud.githubusercontent.com/assets/5491151/16633909/6c1571b6-4399-11e6-8158-305ef03dcdb8.png)
### Live Demo

Kind of hard to wire up a live demo since jsbin only lets you have one file and you need 2 -- one for the app, one for a custom element that uses the localize behavior.

Basically do this in `element.html`:

``` html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../app-localize-behavior/app-localize-behavior.html">
<script>
    Polymer({
        is: 'test-element',
        behaviors: [ Polymer.AppLocalizeBehavior ],
        ready: function() {
            Polymer.dom(this.root).appendChild(
                document.createTextNode(
                    this.localize('myHome')
                )
            );
        }
    });
</script>
```

And then import and consume `<test-element>` in your Polymer application.
### Steps to reproduce
1. Use the `app-localize-behavior` in a custom element inside your application
2. Open the page in IE10
3. Notice the app fails to load and the above JavaScript error is present
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
This should be fixed
