### ISSUE TITLE
pathToResources exists but isn't used, should probably get deleted

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/app-localize-behavior#33]

**Comment by dgabrielli76** [comment]
Maybe this issue should close the #19?

**Comment by dgabrielli76** [comment]
Concerning this issue, I made a PR (#21) to solve it,the unit test was missing, but if you want to delete this property it is useless to do this unit test. Please tell me what you are going to do with this property, if you want to keep it I will re-open the PR and see how to do the unit test.

**Comment by notwaldorf** [comment]
@dgabrielli76 I think we should probably delete the property, hence the `breaking-change` label.

**Comment by dgabrielli76** [comment]
OK @notwaldorf, so there is no needing to re-open the PR.

**Comment by notwaldorf** [comment]
@dgabrielli76 do you want to send a PR to delete this property? :)
