### ISSUE TITLE
The dolar symbol does not show correctly in french

### ISSUE THREAD

**Issue by felixzapata** [PolymerElements/app-localize-behavior#34]
### Description
The demo in french should show the currency according the localize.

[According with the `Intl.NumberFormat` specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat), you can set the language to format the currency, but you only can set the options of the format, not the locales attribute.

### Expected outcome

La vente commence le Jan 1, 1970 à 1:00 AM. Tout est à 10,00 $US

### Actual outcome

La vente commence le Jan 1, 1970 à 1:00 AM. Tout est à $10.00.

### Steps to reproduce

1. Open the demo
2. Change to french.

**Comment by notwaldorf** [comment]
Hmm, the demo defines a USD [currency](https://github.com/PolymerElements/app-localize-behavior/blob/master/demo/x-local-translate.html#L58), and passes it down to the `format.js` library, which does the actual translation. Maybe there's a problem there?

**Comment by felixzapata** [comment]
It is possible. I'm not sure. To check the correct value I tested with the stantard API (It is what the library does underhood). If you try this in the console:

```js
var number = 10;
// request a currency format
console.log(new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'USD' }).format(number));
// → 10,00 $US
```

I will try to investigate what is the problem

**Comment by felixzapata** [comment]
After another quick test, the library FormarJS works fine:

```html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <script src="dist/intl-messageformat.min.js"></script>
    <script>
        (function() {
          var msg = new IntlMessageFormat('The price is: {price, number, USD}', 'fr-FR', {
              number: {
                  USD: {
                      style   : 'currency',
                      currency: 'USD'
                  }
              }
          });
          var output = msg.format({price: 10});
          console.log(output); // => The price is: 10,00 $US
        })();

    </script>
  </head>
  <body></body>
</html>
```

I will take a look and try to discover why is failing in the component.

**Comment by felixzapata** [comment]
@notwaldorf I've found the problem. I will make a PR.
