### ISSUE TITLE
localize throws an error when the resources for a language have not been loaded

### ISSUE THREAD

**Issue by abendigo** [PolymerElements/app-localize-behavior#41]
### Description

localize throws an error when the resources for a language have not been loaded

### Expected outcome

the same result as when resources are not loaded, or language is not set (return undefined)

### Actual outcome

    Error: Cannot read property 'greeting' of undefined
                  x-translate.<anonymous> at /components/app-localize-behavior/app-localize-behavior.html:214
       x-translate._annotatedComputationEffect at /components/polymer/polymer.html:1642
               x-translate._effectEffects at /components/polymer/polymer.html:1449
              x-translate._propertySetter at /components/polymer/polymer.html:1433
                x-translate.__setProperty at /components/polymer/polymer.html:1442
               x-translate._computeEffect at /components/polymer/polymer.html:1629
               x-translate._effectEffects at /components/polymer/polymer.html:1449
              x-translate._propertySetter at /components/polymer/polymer.html:1433
                       x-translate.setter at /components/polymer/polymer.html:1512
                      Context.<anonymous> at basic.html:138

### Steps to reproduce

1. Add app-localize-behavior to an element
2. set language to a value you don't have a resource loaded for (ie: 'foo')
3. call localize('key')

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by felixzapata** [comment]
+1
