### ISSUE TITLE
Support for &nbsp;

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/app-localize-behavior#45]
Could you add support for `&nbsp;`?

**Comment by notwaldorf** [comment]
I don't understand what this issue means. Can you elaborate, please?

**Comment by JosefJezek** [comment]
I need use &nbsp; in locales. Function `localize` doesn't support HTML Entities.

http://www.w3schools.com/html/html_entities.asp

**Comment by notwaldorf** [comment]
`&nbsp` in the keys or values? Can you please provide a JSBin with repro steps where this breaks?

**Comment by JosefJezek** [comment]
`&nbsp` in values. I need use `innerHTML` of element. Polymer don't support HTML in data binding. :-(

**Comment by jorgecasar** [comment]
@JosefJezek you can use this:

```
<my-element inner-h-t-m-l="something&nbsp;whith&nbsp;spaces"></my-element>
```

**Comment by JosefJezek** [comment]
I create `<s-html>` for this issue.

https://github.com/PolymerElements/app-localize-behavior/issues/50#issuecomment-249723032
