### ISSUE TITLE
Error SourceMap after build by custom-build of Polymer.

### ISSUE THREAD

**Issue by pongpanot-t** [PolymerElements/app-localize-behavior#47]
I guess "intl-messageformat" has been bundled in build file
therefore browser can not call SourceMap.

Example : Failed to parse SourceMap: http://localhost:8080/src/intl-messageformat.min.js.map

Sorry to Problem.

**Comment by notwaldorf** [comment]
I'm not sure I understand the problem. I can't access your localhost :(
Closing this as there's no repro steps, but pls reopen if you have a link to a jsbin or something where we can look at this problem
