### ISSUE TITLE
New lines in resource string

### ISSUE THREAD

**Issue by ndvalkov** [PolymerElements/app-localize-behavior#50]
How do you process a longer `JSON` string with new lines in it? `<br/>` gets escapes, `\n` or `\\n\\n` do nothing or break, tried `<pre>` to wrap the localize placeholder, didn't work either. Only way I see is to split the resource into smaller ones, which is not quite OK.

**Comment by notwaldorf** [comment]
I'm not sure that's possible in the underlying [format.js](http://formatjs.io/) library we're using, since the behaviour is just marshalling attributes to them. Does your example work there?

**Comment by ndvalkov** [comment]
No idea. I need it for just a couple of text blocks and it's an informal project, so I'll just split into separate resources for the paragraphs. Thanks.

**Comment by JosefJezek** [comment]
@ndvalkov You need use `innerHTML` of element.

**Comment by gaxolio** [comment]
@JosefJezek , how can I use innerHTML if I need to localize into :
<paper-tooltip for="xyz">[[localize('xyz')]]</paper-tooltip>
<paper-tooltip> works when I put in content something like: aaa <br /> bbb
<paper-tooltip> does not works if I put in content [[localize('xyz')]].
It display "aaa <br /> bbb".
Thanks

**Comment by JosefJezek** [comment]
@gaxolio Please post better example of issue...

**Comment by gaxolio** [comment]
@JosefJezek, here a better example:
this is from "locales.json" , "en" section
"tooltipXyz": "<br />Bytes added/removed from ingress to egress. <br />Ingress UNI Pop: -4. <br />Egress MPLS (Remote) with 1 label: +4",

this code inside the tag <paper-tooltip> show 3 lines when the mouse is hover.
<paper-tooltip for="ingressEgressProcessing"><br />
Bytes added/removed from ingress to egress. <br />
Ingress UNI Pop: -4.<br />
Egress MPLS (Remote) with 1 label: +4",
</paper-tooltip>

this code instead, show the string with the "<br /> included.
<paper-tooltip for="ingressEgressProcessing">[[localize('tooltipXyz')]]</paper-tooltip>
"<br />Bytes added/removed from ingress to egress. <br />Ingress UNI Pop: -4.<br />Egress MPLS (Remote) with 1 label: +4","

I hope I was clear.
Sergio

**Comment by JosefJezek** [comment]
`<paper-tooltip for="ingressEgressProcessing"><s-html html="[[localize('tooltipXyz')]]"></s-html></paper-tooltip>`

https://github.com/StartPolymer/s-html

`bower i StartPolymer/s-html -S`

**Comment by gaxolio** [comment]
@JosefJezek . 
Many thanks for your help.
It works!.

**Comment by Sinjins** [comment]
Excellent @JosefJezek.  Another thanks.

**Comment by notwaldorf** [comment]
Closing this, as this seems to be resolved? Let me know if I misunderstood and I'll reopen it
