### ISSUE TITLE
Private properties and function without prefix '_'

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/app-localize-behavior#53]
Why this behavior using private properties and `loadResources` function without prefix `_`?

I include this behavior to every page element.
https://github.com/StartPolymer/progressive-web-app-template/blob/master/src/app-pages/app-page-404/app-page-404.html

**Comment by notwaldorf** [comment]
If it doesn't have a _, then `loadResources` is a public function -- if you look at the examples, it's needed so that you can load the json translations as you need.
