### ISSUE TITLE
README.md confusing note 

### ISSUE THREAD

**Issue by hyyan** [PolymerElements/app-localize-behavior#62]
Is this still required ?

> 
Note that if you're on a browser that does not natively support the Intl object, you must load the polyfill yourself. An example polyfill can be found here.
>

**Comment by notwaldorf** [comment]
Yes, Intl is still not supported on IE11, Safari 9, etc. If you want to support those browsers, you need to use the polyfill.

**Comment by hyyan** [comment]
I understand that we need the polyfill , but do we need to do it by our own or the behavior is already doing this for us . so far the behavior seems to working perfectly on IE11 after testing with two languages (EN , DE)  , Am I missing something or ..?? 

Thanks in advance

**Comment by notwaldorf** [comment]
The behaviour does not include the polyfill. If you check the source code
for the demo, you'll see that the demo is including the polyfill, not the
behaviour.

I believe Safari 9 does not have Intl, for example.

**Comment by hyyan** [comment]
@notwaldorf   I see , you are correct I have missed the import part in the demo , Everything is clear now , Thanks for your help and Great work  👍
