### ISSUE TITLE
Possible documentation correction needed

### ISSUE THREAD

**Issue by RyanCopley** [PolymerElements/app-localize-behavior#67]
So first off, I'm fairly new to Polymer and its documentation system, but I noticed that between this 

PR: https://github.com/PolymerElements/app-localize-behavior/pull/55, 
this code: https://github.com/PolymerElements/app-localize-behavior/blob/master/app-localize-behavior.html#L247-L251
and this documentation: https://elements.polymer-project.org/elements/app-localize-behavior?active=Polymer.AppLocalizeBehavior#method-loadResources

That the `events` on the documentation haven't been updated:  https://i.imgur.com/RelrNad.png

Not sure how to fix this myself, but I thought i'd point it out:)

**Comment by RyanCopley** [comment]
My suggestion:


app-resources-error -> app-localize-resources-error
app-resources-loaded -> app-localize-resources-loaded

**Comment by notwaldorf** [comment]
Oh! These are fixed in master (https://github.com/PolymerElements/app-localize-behavior/blob/master/app-localize-behavior.html#L103), I guess we haven't done a re-push of the catalog to update it

**Comment by RyanCopley** [comment]
Yeah I noticed they were fixed in the project but wasn't sure what had to happen to republish it to that site:)

**Comment by notwaldorf** [comment]
Working with @blasten on redeploying the site. Closing this!
