### ISSUE TITLE
app-localize-behavior appears to be broken on Safari 9.1 with Polymer 1.8

### ISSUE THREAD

**Issue by rasto68** [PolymerElements/app-localize-behavior#74]
### Description
I have a project that has been working quite happily on Safari 9.1 using Polymer 1.7. Yesterday I upgraded Polymer to 1.8 which also pulled in a new version of the webcomponent.js polyfills and my app stopped working on Safari 9.1 with the following error:

'undefined is not an object (evaluating 'proto.__localizationCache.ajax')

This error doesn't occur when using Safari 10.0.3.

I reverted the polymer/webcomponents.js upgrade and the problem went away.

### Expected outcome

app-localize-behavior should work with the latest version of Polymer and webcomponents.js on Safari 9.1 unless you are planning to drop support for 9.1

### Actual outcome

See description above

### Live Demo
Not possible as our app lives behind a corporate firewall

### Steps to reproduce

Create an application that makes use of app-localize-behavior and attempt to view that app on Safari 9.1

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ X] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by rasto68** [comment]
I forgot to mention that my application is being 'vulcanized' just in case that has any bearing on the issue.

**Comment by rasto68** [comment]
Looks like https://github.com/PolymerElements/app-localize-behavior/pull/65 may fix this :)

**Comment by notwaldorf** [comment]
Closing, as this should be fixed by #65
