### ISSUE TITLE
[Feature Request] Customize Header

### ISSUE THREAD

**Issue by 200Puls** [PolymerElements/app-localize-behavior#78]
It would be useful to add the possibility to customize the header that is sent when loading resources.

We are managing our translations using a translation service that expects an authentication token. So this would allow us to easily send those tokens.

**Comment by notwaldorf** [comment]
Can't a different element be responsible for loading the resources and putting them in a json file? When I built the `loadResources` method I assumed it was loading them from a _local_ path, not the server.

Alternatively: the element implementing this behaviour can load the translations however it wants, and then populate the `resources` object.
