### ISSUE TITLE
How to use polymer data-binding with app-localize-behavior?

### ISSUE THREAD

**Issue by Mika83AC** [PolymerElements/app-localize-behavior#80]
Hello everyone,

I just started to use the app-localize-behavior and got stuck at the second thing I tried.

Translating a "fixed" string for sure is easy with 
`<div>{{localize('greeting')}}</div>`

But how to translate a "variable" string containing a polymer data-binding variable?

Example in fixed language which is working:
`<div>Welcome [[username]]</div>`
The output is "Welcome Peter".

But how to accomplish this with app-localize-behavior? I've tried the most obvious
`<div>{{localize('greeting', 'name', [[username]])}}</div>`
but the output is "{{localize('Welcome', 'name', Peter)}}" and not "Welcome Peter" like expected.

As the documentation doesn't respect this use case, I'm already stuck.

Please help :)

Regards,
Michael

**Comment by H3dz** [comment]
There's already a two-way binding, just remove the double brackets.

`<div>{{localize('greeting', 'name', username)}}</div>`

**Comment by Mika83AC** [comment]
Oh, ok, great! Thank you!

To be true: with a little bit more thinking I should have figured it out for myself ..., it's obvious ... sorry :D
