### ISSUE TITLE
The computed property localize doesn't work inside a dom-if template

### ISSUE THREAD

**Issue by RoXuS** [PolymerElements/app-localize-behavior#9]
### Description
The computed property localize doesn't work inside a dom-if template.

### Expected outcome

The message is displayed.

### Actual outcome

The message is not displayed.

### Steps to reproduce

In your demo `x-translate.html` just insert 
```
        <template is="dom-if" if="[[test]]">
          Test<div>{{localize('sale', 'start', 150, 'time', 15, 'price', 10)}}</div>
        </template>

Polymer({...
        test: {
          type: Boolean,
          value: true
        }
...});
```

`Test` is displayed but the message is not displayed.

![Example](https://cloud.githubusercontent.com/assets/3296671/15422912/2698daee-1e7b-11e6-891d-b9ee57e8e837.png)

**Comment by kevinpschaaf** [comment]
This issue is fixed in Polymer master per #3519; should work after the next Polymer release.

**Comment by notwaldorf** [comment]
@RoXuS I think there's been a new Polymer release today -- would you mind double checking that this works for you now?

**Comment by RoXuS** [comment]
@notwaldorf yeah it is ok with https://github.com/Polymer/polymer/tree/v1.5.0.

Thx !

**Comment by notwaldorf** [comment]
Yay! Closing!
